package edu.isi.oba.ontology.restrictions;

public enum RestrictionKind {
	OBJECT_SOME_VALUES_FROM,
	OBJECT_ALL_VALUES_FROM,
	OBJECT_MIN_CARDINALITY,
	OBJECT_MAX_CARDINALITY,
	OBJECT_EXACT_CARDINALITY,
	OBJECT_HAS_VALUE,
	OBJECT_ONE_OF,
	OBJECT_COMPLEMENT_OF,
	OBJECT_INTERSECTION_OF,
	OBJECT_UNION_OF,

	DATA_SOME_VALUES_FROM,
	DATA_ALL_VALUES_FROM,
	DATA_MIN_CARDINALITY,
	DATA_MAX_CARDINALITY,
	DATA_EXACT_CARDINALITY,
	DATA_HAS_VALUE,
	DATA_ONE_OF,
	DATA_COMPLEMENT_OF,
	DATA_INTERSECTION_OF,
	DATA_UNION_OF,

	UNKNOWN
}
