language: java

script:
  - mvn --settings pom.xml org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=${TRAVIS_TAG:-dev} 1>/dev/null 2>/dev/null 
  - mvn package
  
deploy:
  - provider: releases
    token: $GITHUB_TOKEN
    file: 
      - target/oba-$TRAVIS_TAG-jar-with-dependencies.jar
    skip_cleanup: true
    on:
      tags: true
    overwrite: true

