ontologies:
  modelCatalog:
    xmlUrl: https://mintproject.github.io/Mint-ModelCatalog-Ontology/release/1.2.0/ontology.xml
    prefix: sdm
    prefixUri: https://w3id.org/okn/o/sdm#
  softwareDescription:
    xmlUrl: https://knowledgecaptureanddiscovery.github.io/SoftwareDescriptionOntology/release/1.4.0/ontology.xml
    prefix: sd
    prefixUri: https://w3id.org/okn/o/sd#
name: modelcatalog
output_dir: outputs
openapi_base: modelcatalog_info.yaml

endpoint:
  url: https://endpoint.mint.isi.edu/modelCatalog-1.2.0
  prefix: https://w3id.org/okn/i/mint/
  graph_base: http://ontosoft.isi.edu:3030/modelCatalog-1.2.0/data/

firebase:
  key:


custom_paths:
  /custom/configurationsetups/{id}:
    get:
      description: Gets the details of a single instance of a ModelConfigurationSetup
      parameters:
        - description: Username to query
          in: query
          name: username
          required: false
          schema:
            type: string
        - description: The ID of the resource
          in: path
          name: id
          required: true
          schema:
            type: string
        - description: Name of the custom query
          in: query
          name: custom_query_name
          required: false
          schema:
            type: string
            default: custom_configurationsetups
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelConfigurationSetup'
          description: Gets the details of a single instance of  ModelConfigurationSetup
      summary: Get a ModelConfigurationSetup
      tags:
        - ConfigurationSetup
