site_name: OBA documentation
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - OBA features: features.md
  - Configuration file: configuration_file.md
theme: readthedocs
markdown_extensions:
  - admonition