site_name: OBA documentation
nav:
  - Home: index.md
  - OBA features: features.md
  - "Generate an OpenAPI specification":
      - "Quickstart...": "quickstart.md"
      - "Class filtering": "filtering.md"
      - "OWL to OAS mapping": "mapping.md"
  - Configuration file: "configuration_file.md"
  - Examples: examples.md
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
