site_name: OBA documentation
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - OBA features: features.md
  - Configuration file: configuration_file.md
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true