site_name: OBA documentation
nav:
  - Home: index.md
  - OBA features: features.md
  - Quickstart: quickstart.md
  - OBA Output: result.md
  - Generating the server: server.md
  - Running the server: running_server.md
  - Adding custom queries: adding_custom_queries.md
  - Configuration file: configuration_file.md
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true