ontologies:
  #- http://purl.org/net/p-plan # Regularly unreachable...
  - https://www.opmw.org/p-plan.owl
name: p-plan
output_dir: outputs

openapi:
  openapi: 3.0.1
  info:
    description: Example of the P-Plan ontology
    title: P-Plan
    version: v1.0.0
  externalDocs:
    description: P-Plan
    #url: http://purl.org/net/p-plan
    url: https://www.opmw.org/model/p-plan/

firebase:
  key:

#endpoint not used for this example.
endpoint:
  url: http://endpoint.mint.isi.edu/example
  prefix: https://w3id.org/okn/i/example
  graph_base: http://endpoint.mint.isi.edu/example

path_config:
  enable_get_paths: true
  enable_post_paths: false
  enable_delete_paths: false
  enable_put_paths: false

follow_references: true
