package edu.isi.oba.config;

public enum CONFIG_FLAG {
	ALWAYS_GENERATE_ARRAYS,
	DEFAULT_DESCRIPTIONS,
	DEFAULT_PROPERTIES,
	DISABLE_ALL_PATHS,
	FIX_SINGULAR_PLURAL_PROPERTY_NAMES,
	FOLLOW_REFERENCES,
	GENERATE_JSON_FILE,
	PATH_DELETE,
	PATH_GET,
	PATH_PATCH,
	PATH_POST,
	PATH_PUT,
	REQUIRED_PROPERTIES_FROM_CARDINALITY,
	USE_INHERITANCE_REFERENCES,
	USE_KEBAB_CASE_PATHS,
}
