package edu.isi.oba.config.flags;

public enum ConfigFlagType {
	ALWAYS_GENERATE_ARRAYS,
	DEFAULT_DESCRIPTIONS,
	DEFAULT_PROPERTIES,
	DISABLE_ALL_PATHS,
	ENABLE_GET_ALL_PATHS,
	ENABLE_GET_BY_ID_PATHS,
	FIX_SINGULAR_PLURAL_PROPERTY_NAMES,
	FOLLOW_REFERENCES,
	GENERATE_JSON_FILE,
	PATH_GET_ALL,
	PATH_GET_BY_ID,
	PATH_GET_BY_ID_RESPONSE_ARRAY,
	PATH_DELETE,
	PATH_PATCH,
	PATH_POST,
	PATH_PUT,
	REQUIRED_PROPERTIES_FROM_CARDINALITY,
	USE_COMMON_DEFAULT_PATH_RESPONSES,
	USE_INHERITANCE_REFERENCES,
	USE_KEBAB_CASE_PATHS,
	VALIDATE_GENERATED_OPENAPI_FILE
}
